### ISSUE TITLE
peekData*E is wrong

### ISSUE THREAD

**Issue by codehz** [PMunch/binaryparse#16]
it will ***only*** read the first byte, since peek won't move the position...
https://github.com/PMunch/binaryparse/blob/5f8f4a745ffded841975cd1166b328ee843ff81a/binaryparse.nim#L141-L153

**Comment by PMunch** [comment]
Not sure how I've missed that, and how it hasn't broken anything yet. Good catch!

**Comment by PMunch** [comment]
Sorry this has taken so long, fixed in: https://github.com/PMunch/binaryparse/commit/7508fa718bc9bd53a87024081de6f1fdec9bb762
