### ISSUE TITLE
How to use a socket as input

### ISSUE THREAD

**Issue by bluemax75** [PMunch/binaryparse#6]
Is there a way of using a socket connection directly as a stream?
I only see examples of StringStream and FileStream but don't know how to get data from a socket

**Comment by PMunch** [comment]
Unfortunately sockets don't have a stream defined for them in the stdlib. This means that you have to implement the stream interface over the stream yourself. If you look at the [`StreamObj`](https://nim-lang.org/docs/streams.html#StreamObj) you can see which procedures you'd need to implement. I don't think all of those are required for `binaryparse` though, and things like `setPosition` is only used to go forward in `binaryparse` so you can get away with implementing it as a writing of 0 bytes and discarding of input data for a read.

**Comment by bluemax75** [comment]
Thank you for the prompt and most complete response. Thought it might be the case but wanted to make sure.
